Improve criterions
p-gw/FactorRotations.jl pull request #66
Opened 2024-04-25 16:23 UTC by alyst

Another pass on optimizing criterion performance:
  * replace `Ones() * M` and similar constructs with `sum(M, dims=...)` -- it should be faster
  * replace `tr(A * B)` with `dot(A, B)` where possible -- should be much faster
  * more uses of `∇Q` (if available) as a temporary matrix for intermediate operations to reduce memory footprint
  * simplify and unify the criterion code for CF and Oblimin (now it is more apparent that it's a weighted sum of column and row sums)
  * add Equamax and Parsimax on top of the generalized CF/Oblimin criterion code
  * TargetRotation: skip weighting if all target matrix elements are specified

2024-04-26 00:17 UTC, alyst commented on src/methods/geomin.jl
> +        ∇Q .= Λ ./ Λsq .* part
```suggestion
        ∇Q .= (2 / k) .* Λ ./ Λsq .* part
```

2024-04-29 12:27 UTC, p-gw requested changes
Thanks, looks very good. We can merge this after the minor changes I proposed. 

Also, can you add `Parsimax` and `Equamax` to the `rotation_methods` docs for completeness? 

closes #27; closes #28

2024-04-29 12:27 UTC, p-gw commented on src/methods/oblimin.jl
> +- *γ = p/2*: [`Equamax`](@ref)
Can we add the equivalency for `Parsimax` as well?

2024-04-29 12:27 UTC, p-gw commented on src/utils.jl
> +# generic function for calculating the
use proper docstrings here

2024-04-29 12:27 UTC, p-gw commented on src/utils.jl
> +function weighted_sums_criterion_and_gradient!(
I think `weighted_sums_criterion_and_gradient!` should live in src/methods/methods.jl instead.

2024-04-30 06:19 UTC, alyst commented
@p-gw Thank you for the review. I've addressed your comments + tweaked the infomax and biquartimin.

2024-04-30 08:17 UTC, p-gw approved these changes
Thanks, very nice PR!

2024-04-30 08:17 UTC, merged